### ISSUE TITLE
Wat bugs in Toon app

### ISSUE THREAD

**Issue by Ricardo1320-del** [Luc-S/Toon-HASS#20]
Heb wat bugs gevonden in de Toon app:

1: SSL is niet aan te vinken. Neem aan dat dit een switch hoort te zijn?

2: Legacy password is niet aan te vinken.

3: Het wegschrijven in .json bestand gaat niet goed. Heb hem handmatig moeten aanpassen.

4: Schakelen van de schakelaars gaat niet, omdat je de switch mis.

Ga proberen met je mee te kijken of het te fixen.

**Comment by Luc-S** [comment]
Alle punten worden volgens mij veroorzaakt door het ontbreken van de switches. Ik hoopte dat het probleem inmiddels was verholpen, welke versie van de ToonStore gebruik je?

Je kan wat meer info over dit probleem vinden op domoticaforum.eu vanaf deze post: [https://www.domoticaforum.eu/viewtopic.php?f=99&t=12078&start=60#p92058](https://www.domoticaforum.eu/viewtopic.php?f=99&t=12078&start=60#p92058)

Als je wat kan vinden dan hoor ik het graag!

**Comment by Ricardo1320-del** [comment]
Hoi Luc.

Switches zijn opgelost. Afbeeldingen waren nog niet aanwezig in de resourcefile die de images laad van de custom apps tegenwoordig.
Ik heb ze laten toevoegen voor je, ga nu de resourcefile testen.

Andere punt wat betreft json file, kijk ik morgen weer even na, moet ook simpel op te lossen zijn.

**Comment by Luc-S** [comment]
Ok top! Dankjewel :)

**Comment by Ricardo1320-del** [comment]
Hoi Luc,

Issues zijn inmiddels opgelost. Heb de wijzigingen aangeboden om te verwerken in ToonStore.
